ci: remove on pull_request since GH_TOKEN is unable to be read there
/home/runner/work/.github/.github/task/src/query.ts:7
    throw new Error("请设置和提供 GH_TOKEN，比如 `GH_TOKEN: ${{ secrets.GH_TOKEN }}`");
          ^
Error: 请设置和提供 GH_TOKEN，比如 `GH_TOKEN: ${{ secrets.GH_TOKEN }}`
    at Module.gh_token (/home/runner/work/.github/.github/task/src/query.ts:7:11)
    at main (/home/runner/work/.github/.github/task/src/index.ts:17:45)
    at <anonymous> (/home/runner/work/.github/.github/task/src/index.ts:57:1)
    at ModuleJob.run (node:internal/modules/esm/module_job:234:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:473:24)
    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:122:5)